### ISSUE TITLE
Project scope questions

### ISSUE THREAD

**Issue by lawndoc** [0x706972686f/RMM-Catalogue#11]
There are a few programs in the catalog that look like they are only for operating remote control and not for granting remote access. I think these programs should probably be removed since they don't actually grant access to the systems they are installed on. I propose we remove:
- vncviewer.exe
- Royal Server software
- Royal TS software
- Guacamole software

Additionally, there are remote access tools included that are more network tools and not so much RMM software. One example that is already included in this repository is Tailscale. Even though they aren't necessarily RMM, they can still be used by adversaries for persistent access. I think we should take a stance on whether or not to include this type of non-RMM software in the repository, including Tailscale and the following tools:
- CloudFlare Tunnel
- ngrok
- tmate

**Comment by 0x706972686f** [comment]
It's definitely a valuable question to ask. The original intention was to track the different RMM tools that had been seen or used by different ransomware operators or intrusion access brokers, to get ahead of the curve. By identifying the tools organisations and groups could create detection rules, application allow lists and other similar techniques to help protect themselves.

There are obviously bigger issues at play if they can gain a foothold into your network, but still, trying to help provide useful information to teams.

I think your point is an incredibly valid one - all of which have been used by ransomware groups and should be included.

I do think it raises a possible follow up question: what's the best way to present the data? Should it be as simple as providing a column for category, or should we investigate something else?

Definitely interested in hearing thoughts and suggestions.

**Comment by lawndoc** [comment]
I think having a category column sounds like a reasonable way to present it. There will need to be some way to filter out that category of software in case the consumer wants strictly RMM software for some reason, and adding a software category tag to each one is simple and easy to understand.

**Comment by 0x706972686f** [comment]
Done. I've added it in, and added some additional software to try and populate some examples. The categorisation may not be accurate, and hasn't been defined, but it can at least state that process.
